name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - uses: action/checkout@v4
        name: Use Node.js
      - uses: actions/setup-node@v3
        with:
         node-version: '20.x'
      - run: npm run build --if-present
      - run: npm test

